apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 243560554745.dkr.ecr.eu-west-3.amazonaws.com/fesia255:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
