version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
  backend:
    image: devops_backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql 
  frontend:
    image: frontendv10
    container_name: frontend
    ports:
      - "8085:8080"
    depends_on:
      - backend 

volumes:
  mysql-data:
  
  
     
       